### ISSUE TITLE
Activation function for calculating the score of a tripple is missing

### ISSUE THREAD

**Issue by c0der1337** [siddharth-agrawal/Neural-Tensor-Network#1]
Hello,

I think the acitviation function for calculating the score of a tripple after the training is missing.
https://github.com/siddharth-agrawal/Neural-Tensor-Network/blob/master/neuralTensorNetwork.py#L428-L434 and also in getPredictions().

dev_scores[i, 0] += U[rel][k, 0] \* (np.dot(entity_vector_e1.T, np.dot(W[rel][:, :, k], entity_vector_e2)) +
                    np.dot(V[rel][:, k].T, entity_stack) + b[rel][0, k])

I think it should be like this:
test_score += U[rel][k, 0] \* self.activationFunction((np.dot(entity_vector_e1.T, np.dot(W[rel][:, :, k], entity_vector_e2)) +
                    np.dot(V[rel][:, k].T, entity_stack) + b[rel][0, k]))

What do you think?

**Comment by siddharth-agrawal** [comment]
I think the activation function is irrelevant for computing the thresholds. It selects values so as to maximize the accuracy, which is already happening here. In case you get better results, you can reopen the issue.
