### ISSUE TITLE
An error at line 270 of NeuralTensorNetwork.py

### ISSUE THREAD

**Issue by katsuhiko-hayashi** [siddharth-agrawal/Neural-Tensor-Network#3]
Hi Guys!
I don't understand why the following line of NeuralTensorNetwork.py works well.

wrong_filter = (score_pos + 1 > score_neg)[0]

I think you should subtract 1 from ``score_pos''.

wrong_filter = (score_pos - 1 > score_neg)[0]

**Comment by siddharth-agrawal** [comment]
I had asked the same question to the author of the paper, the math checks out. It's been too long since I wrote this to go into it again, closing.
