### ISSUE TITLE
Get entity vectors for examples of 'i'th relation

### ISSUE THREAD

**Issue by apogre** [siddharth-agrawal/Neural-Tensor-Network#5]
File "neuralTensorNetwork.py", line 219, in neuralTensorNetworkCost
    entity_vectors_e1 = entity_vectors[:, e1.tolist()]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by liwei2016** [comment]
I solve this by modifying Line 607 to 
training_data = np.empty((num_examples, 3), dtype=int)
perhaps the default value for dtype of function 'np.empty' was 'int' at that time

**Comment by saurabhhssaurabh** [comment]
Thanks @liwei2016
