### ISSUE TITLE
what is wordIndices.p file

### ISSUE THREAD

**Issue by saurabhhssaurabh** [siddharth-agrawal/Neural-Tensor-Network#6]
What is 'wordIndices.p' file and how is it created ?

**Comment by siddharth-agrawal** [comment]
Sorry, not providing support on this anymore as it's old. Please download the file and figure it out on your own.

**Comment by angryBird2014** [comment]
I want to apply the code into another dataset,but I don't know how the "wordlndices.p" is created?

**Comment by siddharth-agrawal** [comment]
@angryBird2014 I made my intentions clear in the comment above, please figure it out on your own.
